name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-function-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/basic-function/'

  basic-s3-function-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/basic-s3-function/'

  complete-function-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/complete-function/'